<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mapel_model extends CI_Model
{

    public $table = 'mapel';
    public $id = 'id_mapel';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }


    function get_list()
    {
        $query = $this->db->get('mapel');
        return $query;
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_mapel', $q);
	$this->db->or_like('nama_mapel', $q);
	$this->db->or_like('tarif_1', $q);
	$this->db->or_like('tarif_2', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_mapel', $q);
	$this->db->or_like('nama_mapel', $q);
	$this->db->or_like('tarif_1', $q);
	$this->db->or_like('tarif_2', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mapel_model.php */
/* Location: ./application/models/Mapel_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-09 16:25:10 */
/* http://harviacode.com */