<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mengajar_model extends CI_Model
{

    public $table = 'mengajar';
    public $id = 'id_mengajar';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_mengajar', $q);
	$this->db->or_like('id_tentor', $q);
	$this->db->or_like('id_mapel', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('*');
        $this->db->join('tentor', 'tentor.id_tentor = mengajar.id_tentor');
        $this->db->join('mapel', 'mapel.id_mapel = mengajar.id_mapel');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_mengajar', $q);
	$this->db->or_like('mengajar.id_tentor', $q);
	$this->db->or_like('mengajar.id_mapel', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function total_rows_tentor($id,$q = NULL) {
        $this->db->where('mengajar.id_tentor', $id);
        /*$this->db->like('id_mengajar', $q);
    $this->db->or_like('id_tentor', $q);
    $this->db->or_like('id_mapel', $q);*/
    $this->db->from($this->table);
        return $this->db->count_all_results();
    }
     function get_limit_data_tentor($id, $limit, $start = 0, $q = NULL) {
        $this->db->where('mengajar.id_tentor', $id);
        $this->db->select('*');
        $this->db->join('tentor', 'tentor.id_tentor = mengajar.id_tentor');
        $this->db->join('mapel', 'mapel.id_mapel = mengajar.id_mapel');
        $this->db->order_by($this->id, $this->order);
       /* $this->db->like('id_mengajar', $q);
    $this->db->or_like('mengajar.id_tentor', $q);
    $this->db->or_like('mengajar.id_mapel', $q);*/
    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mengajar_model.php */
/* Location: ./application/models/Mengajar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-09 16:25:16 */
/* http://harviacode.com */