<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tentor_model extends CI_Model
{

    public $table = 'tentor';
    public $id = 'id_tentor';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_all_data($id) {
            $this->db->where($this->id, $id);
            return $this->db->get('tentor')->result_array();
        }

    public function register_tentor($data) {
        $this->db->insert('tentor', $data);

        
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_tentor', $q);
	$this->db->or_like('nama_tentor', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('no_ktp', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('pendidikan', $q);
	$this->db->or_like('pengalaman', $q);
	$this->db->or_like('prestasi', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('alamat_tentor', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('foto_ktp', $q);
	$this->db->or_like('foto_ijazah', $q);
	$this->db->or_like('foto_profil', $q);
	$this->db->or_like('id_provinsi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_tentor', $q);
	$this->db->or_like('nama_tentor', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('no_ktp', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('pendidikan', $q);
	$this->db->or_like('pengalaman', $q);
	$this->db->or_like('prestasi', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('alamat_tentor', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('foto_ktp', $q);
	$this->db->or_like('foto_ijazah', $q);
	$this->db->or_like('foto_profil', $q);
	$this->db->or_like('id_provinsi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function nonaktifkan_tentor($id)
    {
        $this->db->set('status','Belum Aktif');
        $this->db->where($this->id, $id);
        $query=$this->db->update('tentor');
        return $query;
    }
    function aktifkan_tentor($id)
    {
        $this->db->set('status','Aktif');
        $this->db->where($this->id, $id);
        $query=$this->db->update('tentor');
        return $query;
    }

}

/* End of file Tentor_model.php */
/* Location: ./application/models/Tentor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-09 16:24:35 */
/* http://harviacode.com */